import {Game} from './game.js?v=2a';import {CONFIG,STATES} from './config.js?v=2a';import {LEVELS} from './levels.js?v=2a';
import {ArcadeAPI,qualificationRank,safeStorage} from './api.js?v=2a';import {Particles} from './particles.js?v=2a';import {AudioManager} from './audio.js?v=2a';import {Renderer} from './renderer.js?v=2a';
const $=id=>document.getElementById(id),panel=$('panel'),overlay=$('overlay'),stage=$('stage'),canvas=$('gameCanvas');
const read=(key,fallback)=>{try{const v=JSON.parse(safeStorage.getItem(key));return v??fallback;}catch{return fallback;}};
const number=(key,fallback,min,max)=>{const n=Number(read(key,fallback));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;};
const settings={musicVolume:number('musicVolume',.15,0,1),sfxVolume:number('sfxVolume',.65,0,1),screenShake:read('screenShake',true)!==false&&!matchMedia('(prefers-reduced-motion: reduce)').matches};
let personalBest=number('personalBest',0,0,1000000),unlockedLevel=Math.floor(number('unlockedLevel',1,1,10));
let lastInitials=String(read('lastInitials','AAA')).replace(/[^A-Z0-9]/g,'').padEnd(3,'A').slice(0,3);
const save=(k,v)=>safeStorage.setItem(k,JSON.stringify(v));const fmt=n=>String(n).padStart(6,'0');
const audio=new AudioManager(settings),particles=new Particles(),renderer=new Renderer(canvas,particles),api=new ArcadeAPI();
let screen='menu',runId='',endingToken=0,latestRows=[],notice='',qualifyingRank=null,submitted=false;
export const game=new Game({onEvent:(name,data)=>{audio.play(name);renderer.event(name,data,settings);},onState:state=>{stage.dataset.state=state;stateChanged(state);}});
const demo=new Game();demo.start(1);demo.launch();
function button(label,action,kind='secondary',extra=''){return `<button type="button" class="${kind}" data-action="${action}" ${extra}>${label}</button>`;}
function show(html,{pass=false}={}){panel.innerHTML=html;overlay.hidden=false;overlay.classList.toggle('pass-through',pass);panel.classList.toggle('ready-panel',pass);panel.scrollTop=0;}
function heading(title,sub=''){return `<p class="eyebrow">WILLIE / NEON ARCADE</p><h1 class="title">${title}</h1>${sub?`<p class="subtitle">${sub}</p>`:''}`;}
function stats(){return `<div class="stats"><div class="stat"><span>SCORE</span><strong>${fmt(game.score.getScore())}</strong></div><div class="stat"><span>PERSONAL BEST</span><strong>${fmt(personalBest)}</strong></div></div>`;}
function menu(){screen='menu';endingToken++;game.keys.clear();game.transition(STATES.MENU);audio.resume();show(heading('BREAKOUT','Find your angle. Break the system.')+`<p class="eyebrow">10 SECTORS • 7 POWER-UPS • ONE SHARED LEADERBOARD</p><div class="actions">${button('PLAY','play','primary')}${button('LEVEL SELECT','levels')}${button('HIGH SCORES','scores')}${button('SETTINGS','settings')}</div><p class="notice">PERSONAL BEST ${fmt(personalBest)}</p>`);}
function start(level=1){audio.unlock();particles.clear();notice='';submitted=false;qualifyingRank=null;endingToken++;runId=crypto.randomUUID();screen='game';game.start(level);document.activeElement?.blur();}
function stateChanged(state){$('pauseButton').disabled=![STATES.READY,STATES.PLAYING,STATES.PAUSED].includes(state);if(state===STATES.READY){screen='game';audio.resume();show(`<p class="eyebrow">LEVEL ${String(game.level).padStart(2,'0')} / ${LEVELS[game.level-1].name}</p><h2>READY?</h2><p class="subtitle">Move your paddle. Space or tap to launch.</p>${button('LAUNCH','launch','primary')}`,{pass:true});}
 if(state===STATES.PLAYING){overlay.hidden=true;screen='game';audio.resume();}
 if(state===STATES.PAUSED){audio.suspend();show(heading('PAUSED','Take a breath. Your timers are frozen.')+`<div class="actions">${button('RESUME','resume','primary')}${button('RESTART','restart')}${button('MAIN MENU','menu')}</div>`);}
 if(state===STATES.LEVEL_CLEAR){unlockedLevel=Math.max(unlockedLevel,Math.min(10,game.level+1));save('unlockedLevel',unlockedLevel);updateBest();show(heading(game.level===10?'ALL SECTORS CLEAR':'LEVEL CLEAR',LEVELS[game.level-1].name)+stats()+`<div class="actions">${button(game.level===10?'FINISH RUN':'NEXT LEVEL','next','primary')}${button('MAIN MENU','menu')}</div>`);}
 if(state===STATES.GAME_OVER){updateBest();screen='end';show(heading('GAME OVER')+stats()+'<p class="notice">Checking the shared high scores…</p>');void checkQualification(++endingToken);}
}
function updateBest(){personalBest=Math.max(personalBest,game.score.getScore());save('personalBest',personalBest);}
function endScreen(message='',offline=false){show(heading('GAME OVER',game.level===10&&game.bricks.every(b=>b.destroyed||!b.destructible)?'Campaign complete. Beautifully played.':'Another angle. Another chance.')+stats()+`<p class="notice">${message}</p><p class="eyebrow">HIGH SCORE ${latestRows.length?fmt(latestRows[0].score):'—'}</p><div class="actions">${offline?button('SAVE SCORE FOR LATER','offline-initials','primary'):''}${button('RETRY','restart',offline?'secondary':'primary')}${button('HIGH SCORES','scores')}${button('MAIN MENU','menu')}</div>`);}
async function checkQualification(token){try{latestRows=await api.leaderboard();if(token!==endingToken||game.state!==STATES.GAME_OVER)return;qualifyingRank=qualificationRank(game.score.getScore(),latestRows);if(qualifyingRank){game.transition(STATES.ENTER_INITIALS);initialsScreen();audio.play('high_score');renderer.event('high_score',{},settings);}else endScreen('Your run is complete. Challenge the TOP 10 again!');}catch{if(token===endingToken&&game.state===STATES.GAME_OVER)endScreen('Leaderboard temporarily unavailable. Rank cannot be confirmed.',true);}}
function initialsScreen(offline=false){screen='initials';show(heading(offline?'SAVE YOUR RUN':'NEW HIGH SCORE!',offline?'Ranking will be checked when the NAS is available.':`RANK #${qualifyingRank} · provisional until submitted`)+stats()+`<form id="initialsForm"><label for="initials" class="eyebrow">ENTER INITIALS</label><input id="initials" class="initials-input" aria-label="Enter initials" value="${lastInitials}" maxlength="3" minlength="3" pattern="[A-Z0-9]{3}" inputmode="text" autocomplete="off" autocapitalize="characters" spellcheck="false" required><p class="notice">3 CHARACTERS · A–Z / 0–9</p><button class="primary" type="submit">SUBMIT SCORE</button><p id="submitNotice" class="notice" role="status"></p></form><div class="actions">${button('MAIN MENU','menu')}</div>`);$('initials').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);});$('initialsForm').addEventListener('submit',submitInitials);}
async function submitInitials(e){e.preventDefault();if(submitted)return;const input=$('initials'),initials=input.value.toUpperCase();if(!/^[A-Z0-9]{3}$/.test(initials)){input.reportValidity();return;}lastInitials=initials;save('lastInitials',initials);submitted=true;const btn=e.target.querySelector('[type=submit]');btn.disabled=true;const token=endingToken;const result=await api.submit({game_id:'breakout',initials,score:game.score.getScore(),level:game.level,run_id:runId});if(token!==endingToken)return;if(result.rejected){submitted=false;btn.disabled=false;$('submitNotice').textContent=result.message;return;}notice=result.pending?(result.saved?'Score saved on this device. Up to 3 retry attempts on future visits.':'Storage is unavailable; score could not be saved for retry.'):`SCORE SAVED · RANK #${result.rank}`;await leaderboard();}
async function leaderboard(){screen='scores';game.transition(STATES.LEADERBOARD);const token=++endingToken;show(heading('HIGH SCORES','TOP 10 / SHARED NAS LEADERBOARD')+'<p class="notice">Loading…</p>'+button('MAIN MENU','menu'));try{latestRows=await api.leaderboard();if(token!==endingToken)return;const rows=latestRows.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${r.initials}</td><td>${fmt(r.score)}</td><td>${String(r.level).padStart(2,'0')}</td></tr>`).join('');show(heading('HIGH SCORES','TOP 10 / SHARED NAS LEADERBOARD')+`<p class="notice">${notice}</p><table class="score-table"><thead><tr><th>RANK</th><th>INITIALS</th><th>SCORE</th><th>LEVEL</th></tr></thead><tbody>${rows||'<tr><td colspan="4">NO SCORES YET. BE THE FIRST.</td></tr>'}</tbody></table><div class="actions">${button('PLAY','play','primary')}${button('MAIN MENU','menu')}</div>`);}catch{if(token===endingToken)show(heading('HIGH SCORES')+`<p class="notice">Leaderboard temporarily unavailable.</p><p class="notice">${notice}</p><div class="actions">${button('TRY AGAIN','scores','primary')}${button('MAIN MENU','menu')}</div>`);}}
function levels(){screen='levels';show(heading('LEVEL SELECT','Unlocked sectors are saved on this device.')+`<div class="level-grid">${LEVELS.map(l=>button(`${String(l.id).padStart(2,'0')}<small>${l.name}</small>`,'level','secondary',`data-level="${l.id}" ${l.id>unlockedLevel?'disabled aria-label="Locked level '+l.id+'"':''}`)).join('')}</div><p class="notice">Selecting a level starts a new score at zero.</p>${button('MAIN MENU','menu')}`);}
function settingsScreen(){screen='settings';show(heading('SETTINGS','Tune your arcade.')+`<div class="settings-grid"><label>Music volume<input aria-label="Music volume" type="range" id="musicVolume" min="0" max="1" step="0.01" value="${settings.musicVolume}"></label><label>Sound effects<input aria-label="Sound effects" type="range" id="sfxVolume" min="0" max="1" step="0.01" value="${settings.sfxVolume}"></label><label>Screen shake<input type="checkbox" id="screenShake" ${settings.screenShake?'checked':''}></label></div><p class="notice">↔ EXTEND · 15s ／ ↓ SLOW · 10s ／ ♥ EXTRA LIFE · MAX 5</p><p class="notice">✣ MULTI BALL · SPLIT ／ ♨ FIRE BALL · 15s</p><p class="notice">⚡ LASER PADDLE · AUTO 12s ／ ⌁ STICKY PADDLE · 12s</p><p class="notice">Sticky: Space / tap to release. Timed pickups refresh, not stack. All effects reset on life loss.</p><p class="notice">Screen shake: special events only. No ordinary-hit shake.</p><div class="actions">${button('TEST SOUND','sound')}${button('MAIN MENU','menu','primary')}</div>`);for(const key of ['musicVolume','sfxVolume','screenShake'])$(key).addEventListener('input',e=>{settings[key]=key==='screenShake'?e.target.checked:Number(e.target.value);save(key,settings[key]);audio.setVolumes(settings.musicVolume,settings.sfxVolume);});}
panel.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;audio.unlock();switch(el.dataset.action){case'play':start();break;case'launch':game.launch();break;case'menu':menu();break;case'levels':levels();break;case'level':start(Number(el.dataset.level));break;case'scores':void leaderboard();break;case'settings':settingsScreen();break;case'resume':game.resume();break;case'restart':start(game.startLevel);break;case'next':game.nextLevel();break;case'sound':audio.play('powerup_pickup');break;case'offline-initials':game.transition(STATES.ENTER_INITIALS);initialsScreen(true);break;}});
$('pauseButton').addEventListener('click',()=>{audio.unlock();game.state===STATES.PAUSED?game.resume():game.pause();});
const isInput=e=>e.target instanceof Element&&!!e.target.closest('input,select,textarea');
window.addEventListener('keydown',e=>{if(isInput(e))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','a','d',' ','p','Escape'].includes(key)){if(['READY','PLAYING','PAUSED'].includes(game.state))e.preventDefault();audio.unlock();}if(e.repeat&&[' ','p','Escape'].includes(key))return;if(['ArrowLeft','ArrowRight','a','d'].includes(key))game.keys.add(key);if(key===' '&&[STATES.READY,STATES.PLAYING].includes(game.state))game.launch();if(key==='p'||key==='Escape')game.state===STATES.PAUSED?game.resume():game.pause();});
window.addEventListener('keyup',e=>game.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
let drag=null;const pointerX=e=>{const rect=canvas.getBoundingClientRect();return (e.clientX-rect.left)*CONFIG.width/rect.width;};
canvas.addEventListener('pointerdown',e=>{if(!['READY','PLAYING'].includes(game.state))return;audio.unlock();drag={id:e.pointerId,x:e.clientX,y:e.clientY,ready:game.state===STATES.READY||game.balls.some(b=>b.attached)};canvas.setPointerCapture(e.pointerId);game.setPointer(pointerX(e));game.update(0);e.preventDefault();});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||drag?.id===e.pointerId)game.setPointer(pointerX(e));});
canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId){if(drag.ready&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<12)game.launch();drag=null;}});canvas.addEventListener('pointercancel',()=>{drag=null;});
function blur(){game.keys.clear();drag=null;game.pause();audio.suspend();}window.addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
let last=0,hud=0;function frame(t){const dt=last?Math.min(.05,(t-last)/1000):0;last=t;game.update(dt);const useDemo=game.state===STATES.MENU||game.state===STATES.LEADERBOARD;if(useDemo){if(demo.state==='READY')demo.launch();if(demo.state==='LEVEL_CLEAR')demo.nextLevel();if(demo.state==='GAME_OVER')demo.start(1);const b=demo.balls[0];if(b)demo.setPointer(b.x+Math.sin(demo.elapsed*.7)*35);demo.update(dt);}if(game.state!==STATES.PAUSED)renderer.update(dt);renderer.render(useDemo?demo:game,{dim:useDemo});hud+=dt;if(hud>.08){hud=0;$('score').textContent=fmt(game.score.getScore());$('level').textContent=String(game.level||1).padStart(2,'0');$('lives').textContent='♥ '.repeat(game.lives??3).trim();$('lives').setAttribute('aria-label',`${game.lives??3} lives`);}requestAnimationFrame(frame);}
menu();requestAnimationFrame(frame);void api.retryPending();
