import {Game} from './game.js?v=2a-comfort';import {CONFIG,STATES} from './config.js?v=2a-comfort';import {LEVELS} from './levels.js?v=2a-comfort';
import {ArcadeAPI,qualificationRank,safeStorage} from './api.js?v=2a-comfort';import {Particles} from './particles.js?v=2a-comfort';import {AudioManager} from './audio.js?v=2a-comfort';import {Renderer} from './renderer.js?v=2a-comfort';
if(window.self!==window.top)document.documentElement.classList.add('embedded-game');
const $=id=>document.getElementById(id),panel=$('panel'),overlay=$('overlay'),stage=$('stage'),canvas=$('gameCanvas');
const read=(key,fallback)=>{try{const v=JSON.parse(safeStorage.getItem(key));return v??fallback;}catch{return fallback;}};
const number=(key,fallback,min,max)=>{const n=Number(read(key,fallback));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;};
const settings={musicVolume:number('musicVolume',.15,0,1),sfxVolume:number('sfxVolume',.65,0,1),screenShake:read('screenShake',true)!==false&&!matchMedia('(prefers-reduced-motion: reduce)').matches};
let personalBest=number('personalBest',0,0,1000000),unlockedLevel=Math.floor(number('unlockedLevel',1,1,10));
let lastInitials=String(read('lastInitials','AAA')).replace(/[^A-Z0-9]/g,'').padEnd(3,'A').slice(0,3);
const save=(k,v)=>safeStorage.setItem(k,JSON.stringify(v));const fmt=n=>String(n).padStart(6,'0');
const audio=new AudioManager(settings),particles=new Particles(),renderer=new Renderer(canvas,particles),api=new ArcadeAPI();
let screen='menu',runId='',endingToken=0,latestRows=[],notice='',qualifyingRank=null,submitted=false;
export const game=new Game({onEvent:(name,data)=>{audio.play(name);renderer.event(name,data,settings);},onState:state=>{stage.dataset.state=state;stateChanged(state);}});
const demo=new Game();demo.start(1);demo.launch();
const levelName=id=>['初次接觸','霓虹金字塔','交錯激流','中空迷陣','雙重衝擊','鋼鐵之門','電子迴路','硬派連線','能量湧現','最終頻率'][id-1];
function button(label,action,kind='secondary',extra=''){return `<button type="button" class="${kind}" data-action="${action}" ${extra}>${label}</button>`;}
function show(html,{pass=false}={}){panel.innerHTML=html;overlay.hidden=false;overlay.classList.toggle('pass-through',pass);panel.classList.toggle('ready-panel',pass);panel.scrollTop=0;}
function heading(title,sub=''){return `<p class="eyebrow">威力／霓虹街機</p><h1 class="title">${title}</h1>${sub?`<p class="subtitle">${sub}</p>`:''}`;}
function stats(){return `<div class="stats"><div class="stat"><span>分數</span><strong>${fmt(game.score.getScore())}</strong></div><div class="stat"><span>個人最佳</span><strong>${fmt(personalBest)}</strong></div></div>`;}
function menu(){screen='menu';endingToken++;game.keys.clear();game.transition(STATES.MENU);audio.resume();show(heading('BREAKOUT','找準角度，突破極限。')+`<p class="eyebrow">10 大關卡・7 種道具・共享排行榜</p><div class="actions">${button('開始遊戲','play','primary')}${button('選擇關卡','levels')}${button('排行榜','scores')}${button('設定','settings')}</div><p class="notice">個人最佳 ${fmt(personalBest)}</p>`);}
function start(level=1){audio.unlock();particles.clear();notice='';submitted=false;qualifyingRank=null;endingToken++;runId=crypto.randomUUID();screen='game';game.start(level);document.activeElement?.blur();}
function stateChanged(state){$('pauseButton').disabled=![STATES.READY,STATES.PLAYING,STATES.PAUSED].includes(state);if(state===STATES.READY){screen='game';audio.resume();show(`<p class="eyebrow">關卡 ${String(game.level).padStart(2,'0')}／${levelName(game.level)}</p><h2>準備好了嗎？</h2><p class="subtitle">移動擋板，按空白鍵或輕觸發球。擊破 ★ 接道具！</p>${button('發球','launch','primary')}`,{pass:true});}
 if(state===STATES.PLAYING){overlay.hidden=true;screen='game';audio.resume();}
 if(state===STATES.PAUSED){audio.suspend();show(heading('已暫停','稍作休息，所有計時器已暫停。')+`<div class="actions">${button('繼續遊戲','resume','primary')}${button('重新開始','restart')}${button('主選單','menu')}</div>`);}
 if(state===STATES.LEVEL_CLEAR){unlockedLevel=Math.max(unlockedLevel,Math.min(10,game.level+1));save('unlockedLevel',unlockedLevel);updateBest();show(heading(game.level===10?'全關卡通關':'關卡完成',levelName(game.level))+stats()+`<div class="actions">${button(game.level===10?'結束挑戰':'下一關','next','primary')}${button('主選單','menu')}</div>`);}
 if(state===STATES.GAME_OVER){updateBest();screen='end';show(heading('遊戲結束')+stats()+'<p class="notice">正在查詢共享排行榜…</p>');void checkQualification(++endingToken);}
}
function updateBest(){personalBest=Math.max(personalBest,game.score.getScore());save('personalBest',personalBest);}
function endScreen(message='',offline=false){show(heading('遊戲結束',game.level===10&&game.bricks.every(b=>b.destroyed||!b.destructible)?'全關卡通關，打得漂亮！':'換個角度，再挑戰一次。')+stats()+`<p class="notice">${message}</p><p class="eyebrow">最高分 ${latestRows.length?fmt(latestRows[0].score):'—'}</p><div class="actions">${offline?button('暫存分數','offline-initials','primary'):''}${button('再試一次','restart',offline?'secondary':'primary')}${button('排行榜','scores')}${button('主選單','menu')}</div>`);}
async function checkQualification(token){try{latestRows=await api.leaderboard();if(token!==endingToken||game.state!==STATES.GAME_OVER)return;qualifyingRank=qualificationRank(game.score.getScore(),latestRows);if(qualifyingRank){game.transition(STATES.ENTER_INITIALS);initialsScreen();audio.play('high_score');renderer.event('high_score',{},settings);}else endScreen('本次挑戰結束，再次挑戰前十名吧！');}catch{if(token===endingToken&&game.state===STATES.GAME_OVER)endScreen('排行榜暫時無法使用，尚無法確認名次。',true);}}
function initialsScreen(offline=false){screen='initials';show(heading(offline?'儲存本次紀錄':'刷新最高分！',offline?'儲存伺服器恢復連線後將確認排名。':`暫列第 ${qualifyingRank} 名・提交後確認`)+stats()+`<form id="initialsForm"><label for="initials" class="eyebrow">輸入玩家代號</label><input id="initials" class="initials-input" aria-label="輸入玩家代號" value="${lastInitials}" maxlength="3" minlength="3" pattern="[A-Z0-9]{3}" inputmode="text" autocomplete="off" autocapitalize="characters" spellcheck="false" required><p class="notice">3 個字元・限 A–Z／0–9</p><button class="primary" type="submit">提交分數</button><p id="submitNotice" class="notice" role="status"></p></form><div class="actions">${button('主選單','menu')}</div>`);$('initials').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,3);});$('initialsForm').addEventListener('submit',submitInitials);}
async function submitInitials(e){e.preventDefault();if(submitted)return;const input=$('initials'),initials=input.value.toUpperCase();if(!/^[A-Z0-9]{3}$/.test(initials)){input.reportValidity();return;}lastInitials=initials;save('lastInitials',initials);submitted=true;const btn=e.target.querySelector('[type=submit]');btn.disabled=true;const token=endingToken;const result=await api.submit({game_id:'breakout',initials,score:game.score.getScore(),level:game.level,run_id:runId});if(token!==endingToken)return;if(result.rejected){submitted=false;btn.disabled=false;$('submitNotice').textContent=result.message;return;}notice=result.pending?(result.saved?'分數已儲存於此裝置。之後造訪時最多重試 3 次。':'裝置儲存空間無法使用，未能儲存分數以供重試。'):`分數已儲存・第 ${result.rank} 名`;await leaderboard();}
async function leaderboard(){screen='scores';game.transition(STATES.LEADERBOARD);const token=++endingToken;show(heading('排行榜','前十名／共享排行榜')+'<p class="notice">載入中…</p>'+button('主選單','menu'));try{latestRows=await api.leaderboard();if(token!==endingToken)return;const rows=latestRows.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${r.initials}</td><td>${fmt(r.score)}</td><td>${String(r.level).padStart(2,'0')}</td></tr>`).join('');show(heading('排行榜','前十名／共享排行榜')+`<p class="notice">${notice}</p><table class="score-table"><thead><tr><th>排名</th><th>代號</th><th>分數</th><th>關卡</th></tr></thead><tbody>${rows||'<tr><td colspan="4">尚無紀錄，成為第一位挑戰者！</td></tr>'}</tbody></table><div class="actions">${button('開始遊戲','play','primary')}${button('主選單','menu')}</div>`);}catch{if(token===endingToken)show(heading('排行榜')+`<p class="notice">排行榜暫時無法使用。</p><p class="notice">${notice}</p><div class="actions">${button('重試','scores','primary')}${button('主選單','menu')}</div>`);}}
function levels(){screen='levels';show(heading('選擇關卡','已解鎖關卡會儲存在此裝置。')+`<div class="level-grid">${LEVELS.map(l=>button(`${String(l.id).padStart(2,'0')}<small>${levelName(l.id)}</small>`,'level','secondary',`data-level="${l.id}" ${l.id>unlockedLevel?'disabled aria-label="未解鎖關卡 '+l.id+'"':''}`)).join('')}</div><p class="notice">選擇關卡將開始新挑戰，分數從零起算。</p>${button('主選單','menu')}`);}
function settingsScreen(){screen='settings';show(heading('設定','打造你的街機體驗。')+`<div class="settings-grid"><label>音樂音量<input aria-label="音樂音量" type="range" id="musicVolume" min="0" max="1" step="0.01" value="${settings.musicVolume}"></label><label>音效音量<input aria-label="音效音量" type="range" id="sfxVolume" min="0" max="1" step="0.01" value="${settings.sfxVolume}"></label><label>畫面震動<input type="checkbox" id="screenShake" ${settings.screenShake?'checked':''}></label></div><p class="notice">↔ 加寬擋板・失去生命才解除／↓ 減速・10 秒／♥ 額外生命・上限 5 條</p><p class="notice">✣ 多重球・分裂／♨ 火焰球・15 秒</p><p class="notice">⚡ 雷射擋板・自動發射 12 秒／⌁ 黏性擋板・12 秒</p><p class="notice">黏性擋板：按空白鍵或輕觸即可發球。重複取得限時道具會重設時間，不會累加。失去生命時清除所有效果。</p><p class="notice">畫面震動：僅用於特殊事件，一般撞擊不會震動。</p><div class="actions">${button('測試音效','sound')}${button('主選單','menu','primary')}</div>`);for(const key of ['musicVolume','sfxVolume','screenShake'])$(key).addEventListener('input',e=>{settings[key]=key==='screenShake'?e.target.checked:Number(e.target.value);save(key,settings[key]);audio.setVolumes(settings.musicVolume,settings.sfxVolume);});}
panel.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;audio.unlock();switch(el.dataset.action){case'play':start();break;case'launch':game.launch();break;case'menu':menu();break;case'levels':levels();break;case'level':start(Number(el.dataset.level));break;case'scores':void leaderboard();break;case'settings':settingsScreen();break;case'resume':game.resume();break;case'restart':start(game.startLevel);break;case'next':game.nextLevel();break;case'sound':audio.play('powerup_pickup');break;case'offline-initials':game.transition(STATES.ENTER_INITIALS);initialsScreen(true);break;}});
$('pauseButton').addEventListener('click',()=>{audio.unlock();game.state===STATES.PAUSED?game.resume():game.pause();});
const isInput=e=>e.target instanceof Element&&!!e.target.closest('input,select,textarea');
window.addEventListener('keydown',e=>{if(isInput(e))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','a','d',' ','p','Escape'].includes(key)){if(['READY','PLAYING','PAUSED'].includes(game.state))e.preventDefault();audio.unlock();}if(e.repeat&&[' ','p','Escape'].includes(key))return;if(['ArrowLeft','ArrowRight','a','d'].includes(key))game.keys.add(key);if(key===' '&&[STATES.READY,STATES.PLAYING].includes(game.state))game.launch();if(key==='p'||key==='Escape')game.state===STATES.PAUSED?game.resume():game.pause();});
window.addEventListener('keyup',e=>game.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
let drag=null;const pointerX=e=>{const rect=canvas.getBoundingClientRect();return (e.clientX-rect.left)*CONFIG.width/rect.width;};
canvas.addEventListener('pointerdown',e=>{if(!['READY','PLAYING'].includes(game.state))return;audio.unlock();drag={id:e.pointerId,x:e.clientX,y:e.clientY,ready:game.state===STATES.READY||game.balls.some(b=>b.attached)};canvas.setPointerCapture(e.pointerId);game.setPointer(pointerX(e));game.update(0);e.preventDefault();});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||drag?.id===e.pointerId)game.setPointer(pointerX(e));});
canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId){if(drag.ready&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<12)game.launch();drag=null;}});canvas.addEventListener('pointercancel',()=>{drag=null;});
// Portrait thumb pad keeps fingers below the playfield; same logical coordinates.
const touchPad=$('touchPad'),touchLaunch=$('touchLaunch');let padPointer=null;
if(touchPad){const movePad=e=>{const r=touchPad.getBoundingClientRect();game.setPointer((e.clientX-r.left)/r.width*CONFIG.width);game.update(0);};touchPad.addEventListener('pointerdown',e=>{if(!['READY','PLAYING'].includes(game.state)||e.target.closest('button'))return;audio.unlock();padPointer=e.pointerId;touchPad.setPointerCapture(e.pointerId);movePad(e);e.preventDefault();});touchPad.addEventListener('pointermove',e=>{if(e.pointerId===padPointer)movePad(e);});for(const name of ['pointerup','pointercancel'])touchPad.addEventListener(name,()=>{padPointer=null;});}
if(touchLaunch)touchLaunch.addEventListener('click',()=>{audio.unlock();game.launch();});
function blur(){game.keys.clear();drag=null;game.pause();audio.suspend();}window.addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});
let last=0,hud=0;function frame(t){const dt=last?Math.min(.05,(t-last)/1000):0;last=t;game.update(dt);const useDemo=game.state===STATES.MENU||game.state===STATES.LEADERBOARD;if(useDemo){if(demo.state==='READY')demo.launch();if(demo.state==='LEVEL_CLEAR')demo.nextLevel();if(demo.state==='GAME_OVER')demo.start(1);const b=demo.balls[0];if(b)demo.setPointer(b.x+Math.sin(demo.elapsed*.7)*35);demo.update(dt);}if(game.state!==STATES.PAUSED)renderer.update(dt);renderer.render(useDemo?demo:game,{dim:useDemo});hud+=dt;if(hud>.08){hud=0;$('score').textContent=fmt(game.score.getScore());$('level').textContent=String(game.level||1).padStart(2,'0');$('lives').textContent='♥ '.repeat(game.lives??3).trim();$('lives').setAttribute('aria-label',`剩餘 ${game.lives??3} 條生命`);}requestAnimationFrame(frame);}
menu();requestAnimationFrame(frame);void api.retryPending();
