import {CONFIG} from './config.js';import {POWERUP_TYPES} from './powerup.js';
const rounded=(ctx,x,y,w,h,r)=>{ctx.beginPath();ctx.roundRect(x,y,w,h,r);};
export class Renderer{
 constructor(canvas,particles){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.particles=particles;this.flash=0;this.shake=0;this.caption=null;}
 event(name,data,settings){if(name==='brick_break'){this.particles.burst(data.x,data.y,data.color,22);if(settings.screenShake)this.shake=.09;}if(name==='powerup_pickup'){this.particles.burst(data.x,data.y,data.color,38);this.caption={text:data.label,sub:'POWER UP',time:1.3,color:data.color};}if(name==='level_clear')this.flash=.3;if(name==='high_score')this.flash=.65;}
 update(dt){this.particles.update(dt);this.flash=Math.max(0,this.flash-dt);this.shake=Math.max(0,this.shake-dt);if(this.caption){this.caption.time-=dt;if(this.caption.time<=0)this.caption=null;}}
 render(g,{dim=false}={}){const c=this.ctx,W=CONFIG.width,H=CONFIG.height;c.fillStyle='#080d1c';c.fillRect(0,0,W,H);
 const bg=c.createRadialGradient(W*.5,H*.4,20,W*.5,H*.4,760);bg.addColorStop(0,'#132442');bg.addColorStop(1,'#080b18');c.fillStyle=bg;c.fillRect(0,0,W,H);
 c.save();if(this.shake>0)c.translate(Math.sin(this.shake*350)*2,Math.cos(this.shake*420)*2);
 c.strokeStyle='#3b63831c';c.lineWidth=1;for(let x=0;x<W;x+=64){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke();}for(let y=16;y<H;y+=48){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke();}
 c.fillStyle='#39dff8';c.shadowColor='#39dff8';c.shadowBlur=12;c.fillRect(0,0,3,H-32);c.fillRect(W-3,0,3,H-32);c.fillRect(0,0,W,3);c.shadowBlur=0;
 c.textAlign='left';c.font='600 13px ui-monospace,monospace';c.fillStyle='#5a7895';c.fillText('SECTOR '+String(g.level||1).padStart(2,'0')+'   /   NEON ARCADE',36,43);c.textAlign='right';c.fillText('BREAK • REFLECT • REPEAT',W-36,43);
 for(const b of g.bricks){if(b.destroyed)continue;c.save();c.shadowColor=b.color;c.shadowBlur=b.type===4?15:7;const gradient=c.createLinearGradient(b.x,b.y,b.x,b.y+b.height);gradient.addColorStop(0,b.flash>0?'#ffffff':b.color);gradient.addColorStop(1,b.type===3?'#263c57':b.color+'88');c.fillStyle=gradient;rounded(c,b.x,b.y,b.width,b.height,5);c.fill();c.shadowBlur=0;c.strokeStyle=b.color;c.lineWidth=1;c.stroke();c.fillStyle='#ffffff70';c.fillRect(b.x+7,b.y+4,b.width-14,2);if(b.type===2){c.strokeStyle='#251f52';c.lineWidth=2;if(b.hp===1){c.beginPath();c.moveTo(b.x+b.width*.45,b.y);c.lineTo(b.x+b.width*.55,b.y+9);c.lineTo(b.x+b.width*.4,b.y+18);c.lineTo(b.x+b.width*.58,b.y+b.height);c.stroke();}else{c.fillStyle='#261d5f';c.fillRect(b.x+b.width/2-6,b.y+12,4,4);c.fillRect(b.x+b.width/2+2,b.y+12,4,4);}}if(b.type===3){c.fillStyle='#cee3f5';c.fillRect(b.x+8,b.y+12,3,3);c.fillRect(b.x+b.width-11,b.y+12,3,3);}if(b.type===4){c.fillStyle='#463014';c.textAlign='center';c.font='bold 19px system-ui';c.fillText('✦',b.x+b.width/2,b.y+22);}c.restore();}
 for(const p of g.powerups){const type=POWERUP_TYPES[p.type];c.save();c.translate(p.x,p.y);c.rotate(Math.sin(p.age*4)*.09);c.shadowBlur=20;c.shadowColor=type.color;c.fillStyle='#0a152c';rounded(c,-20,-16,40,32,8);c.fill();c.strokeStyle=type.color;c.lineWidth=2;c.stroke();c.fillStyle=type.color;c.textAlign='center';c.font='bold 24px system-ui';c.fillText(type.icon,0,8);c.restore();}
 const p=g.paddle;c.save();c.shadowBlur=24;c.shadowColor='#3ce9ff';const pg=c.createLinearGradient(p.x,p.y,p.x,p.y+p.height);pg.addColorStop(0,'#e6fdff');pg.addColorStop(.35,'#4ce6f7');pg.addColorStop(1,'#147da1');c.fillStyle=pg;rounded(c,p.x,p.y,p.width,p.height,9);c.fill();c.shadowBlur=0;c.fillStyle='#fe72b8';rounded(c,p.x+5,p.y+4,10,p.height-8,4);c.fill();rounded(c,p.x+p.width-15,p.y+4,10,p.height-8,4);c.fill();c.restore();
 for(const b of g.balls){c.save();for(let i=0;i<b.trail.length;i++){const t=b.trail[i];c.globalAlpha=i/b.trail.length*.25;c.fillStyle='#52e7ff';c.beginPath();c.arc(t.x,t.y,b.radius*(i/b.trail.length)*.8,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.shadowBlur=23;c.shadowColor='#9af4ff';c.fillStyle='#fff';c.beginPath();c.arc(b.x,b.y,b.radius,0,Math.PI*2);c.fill();c.restore();}
 this.particles.render(c);c.fillStyle='#ff528544';c.fillRect(20,H-13,W-40,1);c.font='600 16px ui-monospace,monospace';c.fillStyle='#a8deee';c.textAlign='left';let x=32;for(const [type,time] of Object.entries(g.effects)){if(time>0){c.fillText(POWERUP_TYPES[type].icon+' '+time.toFixed(1)+'s',x,H-30);x+=130;}}
 if(this.caption){const t=this.caption;c.save();c.globalAlpha=Math.min(1,t.time*3);c.textAlign='center';c.lineWidth=8;c.strokeStyle='#060914';c.shadowColor=t.color;c.shadowBlur=25;c.font='900 58px system-ui';c.strokeText(t.text,W/2,H*.58);c.fillStyle=t.color;c.fillText(t.text,W/2,H*.58);c.font='bold 22px ui-monospace,monospace';c.fillStyle='#fff';c.fillText(t.sub,W/2,H*.58+35);c.restore();}
 if(this.flash>0){c.fillStyle=`rgba(139,225,255,${this.flash*.3})`;c.fillRect(0,0,W,H);}c.restore();if(dim){c.fillStyle='#0509187a';c.fillRect(0,0,W,H);}
 }
}
