import {test,expect} from '@playwright/test';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8767';
const run=(page,code)=>page.evaluate(async code=>{const src=document.querySelector('script[type="module"]').src;const {game}=await import(src);return Function('g',code)(game);},code);
async function start(page){await page.goto(base);await page.locator('[data-action="play"]').click();}
test('tier upgrades twice in outside status and ability meter is accessible',async({page})=>{await start(page);await run(page,"g.applyPowerup('extend');g.applyPowerup('extend');");await expect(page.locator('#activeEffects')).toContainText('加寬二階');await expect(page.locator('#chargeMeter')).toHaveAttribute('aria-label','蓄力進度');expect(await page.locator('#chargeMeter').evaluate(el=>!el.closest('#stage'))).toBe(true);});


async function flying(page){await start(page);await page.keyboard.press('Space');await run(page,'g.balls[0].x=640;g.balls[0].y=450;g.balls[0].vx=0;g.balls[0].vy=-30;');}
async function point(page){const b=await page.locator('canvas').boundingBox();return {x:b.x+b.width*.5,y:b.y+b.height*.8};}
test('mouse hold charges but Space only launches and release fires once',async({page})=>{await flying(page);await page.keyboard.press('Space');expect(await run(page,'return g.charge?.active||false')).toBe(false);const p=await point(page);await page.mouse.move(p.x,p.y);await page.mouse.down();expect(await run(page,'return g.charge?.active||false')).toBe(true);await page.waitForTimeout(500);await page.mouse.up();expect(await run(page,'return g.chargeShots.length')).toBe(1);expect(await run(page,'return g.chargeShots[0].full')).toBe(false);});
test('keyboard C charge cancels on pause and releasing after resume never fires',async({page})=>{await flying(page);await page.keyboard.down('c');expect(await run(page,'return g.charge?.active||false')).toBe(true);await page.waitForTimeout(450);await page.keyboard.press('p');await page.keyboard.press('p');await page.keyboard.up('c');expect(await run(page,'return {active:g.charge.active,shots:g.chargeShots.length}')).toEqual({active:false,shots:0});});
test('phone canvas drag never charges; outside hold button fires',async({browser})=>{const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await ctx.newPage();await flying(page);await expect(page.locator('#chargeButton')).toBeVisible();const p=await point(page),cdp=await ctx.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await page.waitForTimeout(450);expect(await run(page,'return g.charge.active')).toBe(false);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const b=await page.locator('#chargeButton').boundingBox();expect(b.y).toBeGreaterThan(p.y);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});expect(await run(page,'return g.charge.active')).toBe(true);await page.waitForTimeout(450);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});expect(await run(page,'return g.chargeShots.length')).toBe(1);await ctx.close();});
test('guided pointer changes aim while paddle is frozen and click fires without charge',async({page})=>{await start(page);await run(page,"g.applyPowerup('aim');");expect(await run(page,'return !!g.aimingBall')).toBe(true);await expect(page.locator('#overlay')).toBeHidden();const before=await run(page,'return {x:g.paddle.x,angle:g.aimAngle}');const b=await page.locator('canvas').boundingBox();await page.mouse.move(b.x+b.width*.8,b.y+b.height*.2);expect(await run(page,'return g.aimAngle')).not.toBe(before.angle);expect(await run(page,'return g.paddle.x')).toBe(before.x);await page.mouse.click(b.x+b.width*.8,b.y+b.height*.2);expect(await run(page,'return {aim:!!g.aimingBall,charge:g.charge.active}')).toEqual({aim:false,charge:false});});
